[package]
name = "tsu"
version = "0.1.0"
edition = "2021"
authors = ["freeze-dolphin <freeze-dolphin@outlook.com>"]
license = "BSD-3-Clause"

[dependencies]
osuparse = "*"
rodio = "*"
clap = { version = "*", features = ["derive"] }
cursive = "*"
crossbeam = "*"
